version: '3'

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    volumes:
    - cassandra_data:/var/lib/cassandra

  tank:
    build: .
    environment:
      - TANK_DB_HOSTS=cassandra
      - LOG_PATH=/app/logs
    volumes:
    - tank_log:/app/logs
    ports:
    - '8888:8888'

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.1
    volumes:
      - tank_log:/usr/share/filebeat/logs/tank:ro
    command: |
      bash -c 'bash -s <<EOF
        cat > /usr/share/filebeat/data/filebeat.yml <<EON
          filebeat.inputs:
          - type: log
            enabled: true
            paths:
              - /usr/share/filebeat/logs/tank/*.log
          output.elasticsearch:
            hosts: ["elasticsearch:9200"]
          processors:
          - dissect:
              tokenizer: "%{timestamp} %{+timestamp} %{thread} %{level->} %{logger} %{?minus} %{msg}"
              field: "message"
              target_prefix: "dissect"
          - dissect:
              when:
                contains:
                  dissect.msg: "Start"
              tokenizer: "%{correlationId} %{?minus} %{orderToken} %{event}"
              field: "dissect.msg"
              target_prefix: "dissect"
          - dissect:
              when:
                contains:
                  dissect.msg: "Finish"
              tokenizer: "%{correlationId} %{?minus} %{orderToken} %{event}"
              field: "dissect.msg"
              target_prefix: "dissect"
      EON
       ./filebeat -c data/filebeat.yml -e
      EOF'

volumes:
  cassandra_data:
  tank_log: