version: '3'

services:
  cassandra:
    image: geocode.igd.fraunhofer.de:4567/marauder/cassandra-lucene/master:7f9d4b9bb7dad4567944b29759878687e820d3e5
    volumes:
    - cassandra_data:/var/lib/cassandra

  tank:
    image: geocode.igd.fraunhofer.de:4567/marauder/tank:databio_lucene
    environment:
      - TANK_DB_HOSTS=cassandra
      - LOG_PATH=/app/logs
    volumes:
    - tank_log:/app/logs
    ports:
    - '8888:8888'

volumes:
  cassandra_data:
  tank_log: