version: '3'

services:
  cassandra:
    image: ap3rture/cassandra-lucene:latest
    volumes:
    - cassandra_data:/var/lib/cassandra

  tank:
    image: ap3rture/tank:latest
    environment:
      - TANK_DB_HOSTS=cassandra
      - LOG_PATH=/app/logs
    volumes:
    - tank_log:/app/logs
    ports:
    - '8888:8888'

volumes:
  cassandra_data:
  tank_log: