version: '3'

services:
  cassandra:
    image: cassandra:3.11
    container_name: cassandra
    volumes:
    - cassandra_data:/var/lib/cassandra

  tank:
    build: .
    environment:
      - TANK_DB_HOSTS=cassandra
      - LOG_PATH=/app/logs
    volumes:
    - tank_log:/app/logs
    ports:
    - '8888:8888'

  filebeat:
    image: docker.elastic.co/beats/filebeat:6.6.1
    volumes:
      - tank_log:/usr/share/filebeat/logs/tank:ro
      - $FILEBEAT_CONF_PATH:/usr/share/filebeat/filebeat.yml:ro

volumes:
  cassandra_data:
  tank_log: